# DynamoDB for local development and testing
services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -disableTelemetry -sharedDb
    ports:
      - "8000:8000"
